### ISSUE TITLE
jsonrpc4j : parse error

### ISSUE THREAD

**Issue by sanjeet2014mca** [SubOptimal/spring-boot-jsonrpc4j#1]
Hi,
 We are using the git codes for jsonrpc but getting the below error while calling server..Please help us on this.

![issueinrpcjson](https://cloud.githubusercontent.com/assets/19646873/15646947/3c82f712-267e-11e6-93a0-d295299ab664.PNG)

**Comment by sanjeet2014mca** [comment]
Hi,

I got this issues please help me.
Thanks in advance:

   request:
curl -v -H "Content-Type: application/json" -d '{"id":0, "method":"sayHelloWorld", "params":["John Doe"]}' http://localhost:8080/rpc/myservice

response:
{"jsonrpc":"jsonrpc","id":"null","error":{"code":-32700,"message":"Parse error"}

**Comment by SubOptimal** [comment]
Have a look at the updated [README](https://github.com/SubOptimal/spring-boot-jsonrpc4j/blob/master/README.md). I added an example for Windows. You need to escape the double quotes.

**Comment by sanjeet2014mca** [comment]
Thanks for help, i looked and got solution.

**Comment by sanjeet2014mca** [comment]
Please share some example for JsonServiceExporter with credential (username & password) i want to pass CURL command and get response on console.
thanks in advance ...............
